services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - back/environments/local.env
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    env_file:
      - front/.env
    restart: always

  postgres:
   container_name: postgres_container
   image: postgres:16.1
   restart: always
   env_file:
    - back/environments/docker.env
   volumes:
    - pgdata:/var/lib/postgresql/data
   ports:
    - '5432:5432'

volumes:
  pgdata: