services:
  backend:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - back/environments/droplet.env
    depends_on:
      - postgres
    restart: always
    command: sh -c "npm run migration:run && npm run start:prod" 

  frontend:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    env_file:
      - front/.env.droplet
    restart: always

  postgres:
   container_name: postgres_container
   image: postgres:16.1
   restart: always
   env_file:
    - back/environments/droplet.env
   volumes:
    - pgdata:/var/lib/postgresql/data
   ports:
    - '5432:5432'

volumes:
  pgdata: