apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: registry.digitalocean.com/messenger-registry/nest-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: app-secrets
   
---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  selector:
    app: nest-app
  type: ClusterIP
  ports:
    - name: http-port   # HTTP port exposed externally (Port 80)
      protocol: TCP
      port: 80          # Public port exposed externally for HTTP
      targetPort: 5000  # Internal container port your app runs on
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-http"
spec:
  tls:
    - hosts:
        - messenger-test.duckdns.org
      secretName: messenger-test-cert  # Will be auto-created by cert-manager
  rules:
    - host: messenger-test.duckdns.org
      http:
        paths:
          # Route for the ACME challenge to the ingress controller
          - path: /.well-known/acme-challenge/*
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-controller
                port:
                  number: 80
          # Main application route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nest-service
                port:
                  number: 80
