apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      # serviceAccountName: cert-manager-webhook-duckdns
      containers:
        - name: nest-app
          image: registry.digitalocean.com/messenger-registry/nest-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  selector:
    app: nest-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000


# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nest-app-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"  # Use the NGINX ingress controller
#     cert-manager.io/cluster-issuer: "letsencrypt-dns-issuer"  # Reference the correct ClusterIssuer
#     nginx.ingress.kubernetes.io/websocket-services: "nest-service"
# spec:
#   tls:
#   - hosts:
#       - messenger-test.duckdns.org
#     secretName: messenger-test-cert  # cert-manager will create this secret
#   rules:
#     - host: messenger-test.duckdns.org
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: nest-service
#                 port:
#                   number: 80


# ---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: nginx
# spec:
#   controller: k8s.io/ingress-nginx
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: duckdns-secret
#   namespace: default 
# data:
#   api-token: YmVjYTY1MzUtOWY1YS00MDEyLTg5YzEtNWNjN2VjMjYyZTMz
  
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-dns-issuer
# spec:
#   acme:
#     email: zapishny@ukr.net
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-dns-private-key
#     solvers:
#       - dns01:
#           webhook:
#             groupName: duckdns.webhook.ebrianne.dev
#             solverName: duckdns
#             config:
#               tokenSecretRef:
#                 name: duckdns-secret
#                 key: api-token
