apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: registry.digitalocean.com/messenger-registry/nest-app
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets  # The name of the Kubernetes secret you created
