apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: registry.digitalocean.com/messenger-registry/nest-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  selector:
    app: nest-app
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: 80          # Public port exposed externally for HTTP
      targetPort: 5000  # Internal container port your app runs on

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    email: zapishny@ukr.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http-private-key
    solvers:
      - http01:
          ingress:
            class: nginx  # This is the default class for Nginx Ingress Controller

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Make sure nginx ingress is installed and used
    cert-manager.io/cluster-issuer: "letsencrypt-http"
    nginx.ingress.kubernetes.io/websocket-services: "nest-service"
spec:
  tls:
    - hosts:
        - messenger-test.duckdns.org
      secretName: messenger-test-cert  # The certificate will be created by cert-manager
  rules:
    - host: messenger-test.duckdns.org
      http:
        paths:
          - path: /.well-known/acme-challenge/*
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-controller
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nest-service
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: challenge-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: challenge-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-server
  template:
    metadata:
      labels:
        app: challenge-server
    spec:
      containers:
        - name: challenge-server
          image: nginx:alpine
          volumeMounts:
            - name: challenge-volume
              mountPath: /usr/share/nginx/html/.well-known/acme-challenge
      volumes:
        - name: challenge-volume
          configMap:
            name: acme-challenge-files

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-challenge-files
data:
  "dmJudrgLFnKhmt-cFG7nKSjwxZIxg5kiU0annCFQ8A0": "L9NYCvshXPuZRvblbhwBrY_Ndga8g1e-IyOtJRkPKHE"
