name: CI/CD Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - kuber

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push NestJS image
        run: |
          docker build -t registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/nest-app ./back
          docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/nest-app

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Create Kubernetes Secret for App, JWT, and Postgres
        run: |
         
          kubectl create secret generic app-secrets --from-literal=APP_PORT=${{ secrets.KU_APP_PORT }} 
  
       
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/nest-deployment.yaml
         
